models/courses.py
from app import db
from models.hole import Hole

#Below is for TMA
class HoleUploadInfo(db.Document):
    index = db.ListField(db.StringField())
    par = db.ListField(db.StringField())
    dist = db.ListField(db.StringField())
#Above is for TMA

class Course(db.Document):
    meta = {'collection': 'course'}
    name = db.StringField()
    #TMA
    #holesDetail = db.ReferenceField(HoleUploadInfo)
    #ECA
    holesDetail = db.ListField(db.ReferenceField(Hole))

    image = db.URLField()
    description = db.StringField()

controllers/auth.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from flask import Blueprint, request, redirect, render_template, url_for, flash
from models.form import RegistrationForm
from models.users import User

auth = Blueprint('auth', __name__)

@auth.route("/register", methods=["GET", "POST"])
def register():
    Reg_Form = RegistrationForm(request.form)

    if request.method == "GET":
        return render_template("register.html", RegistrationForm=Reg_Form)

    elif request.method == "POST":
        if Reg_Form.validate():
            aEmail = Reg_Form.email.data
            aPassword = Reg_Form.password.data
            aName = Reg_Form.name.data
            existing_user = User.objects(email=aEmail).first()
            if existing_user is None:
                hashpass = generate_password_hash(aPassword, method='sha256')
                new_user = User(email=aEmail, password=hashpass, name=aName).save()
                return redirect(url_for('auth.login'))
            else:
                Reg_Form.email.errors.append("User already existed")
            return render_template("register.html", RegistrationForm=Reg_Form)

        else:
            return render_template("register.html", RegistrationForm=Reg_Form) 

@auth.route("/", methods=["GET", "POST"])
@auth.route("/login", methods=["GET", "POST"])
def login():
    
    if current_user.is_authenticated == True:
        return redirect(url_for('courses.render_course'))
    else: 
        Log_Form = RegistrationForm(request.form)
        if request.method == "GET":
            return render_template("login.html", RegistrationForm=Log_Form)

        elif request.method == "POST":
            if Log_Form.validate():
                aEmail = Log_Form.email.data
                aPassword = Log_Form.password.data
                check_user = User.objects(email=aEmail).first()
                if check_user:
                    if check_password_hash(check_user['password'], Log_Form.password.data):
                        login_user(check_user)
                        return redirect(url_for('courses.render_course'))
                    else:
                        Log_Form.password.errors.append("User Password Not Correct")
                else:
                    Log_Form.email.errors.append("No Such User")
                    return render_template("login.html", RegistrationForm=Log_Form)
            else:
                return render_template("login.html", RegistrationForm=Log_Form) 

        return render_template("login.html", RegistrationForm=Log_Form)

@auth.route('/logout', methods = ['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

controllers/course.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import login_required, current_user
from models.courses import Course, HoleUploadInfo
from models.hole import Hole
from models.booking import Booking
from models.users import User
import csv, io, datetime

course = Blueprint('courses', __name__)

@course.route('/courses', methods=['GET','POST'])
@login_required
def render_course():
    if request.method == 'POST':
        choiceFlow = request.form.get('type')
        courseSelectedName = request.form.get('courseType')

        return redirect(url_for('courses.render_course_detail', aCourse=courseSelectedName))
    choiceFlow = request.args.get('type')
    if choiceFlow == 'courseBook':
        return render_template('courses.html', aUser=current_user.name, courses=Course.objects(), type=choiceFlow)

    return render_template('courses.html', aUser=current_user.name, courses=Course.objects(), type=choiceFlow)

@course.route('/courseDetail', methods=['GET','POST'])
@login_required
def render_course_detail():
    if request.method == 'POST':
        courseSelectedName = request.form.get('courseType')
        choiceFlow = request.form.get('type')
        tee_time = request.form.get('tee_time')
        courseSelected = Course.objects(name=courseSelectedName).first()
        aUser = User.objects(name=current_user.name).first()
        bookingSelected = Booking.objects(name=aUser, courseName=courseSelected).first()
        new_tee_time = bookingSelected['tee_time']
        tee_time = tee_time.replace("-","/").replace("T"," ")
        tee_time_DT = datetime.datetime.strptime(tee_time,"%Y/%m/%d %H:%M")
        tee_time_DT = [str(tee_time_DT.strftime("%d/%m/%Y %I:%M:%S %p"))]
        new_tee_time.append(tee_time_DT)
        bookingSelected.update(__raw__={'$set': {'tee_time': new_tee_time}})
        return redirect(url_for('courses.render_course', aUser=current_user.name, courses=Course.objects(), type=choiceFlow))
    courseName = request.args.get('aCourse')
    aCourse = Course.objects(name=courseName).first()
    return render_template('courseDetail.html', aUser=current_user.name, aCourse=aCourse, aCourseName=courseName)

@course.route("/upload", methods=['GET','POST'])
@login_required
def upload():
    if request.method == 'GET':
        return render_template("upload.html", aUser=current_user.name)
    elif request.method == 'POST':        
        type = request.form.get('type')
        file = request.files.get('file')                    
        data = file.read().decode('utf-8')
        dict_reader = csv.DictReader(io.StringIO(data), delimiter=',', quotechar='"')
        file.close()
        #after upload successfully - maybe can show some message
        if type == 'booking':
            prev_item_name = None

            #ECA
            prev_name = None

            tee_time_list = []
            for item in list(dict_reader):
                name = User.objects(email=item['user']).first()
                courseName = Course.objects(name=item['course_name']).first()
                tee_time = item['check_in_time'].strip('"').split(", ")
                if prev_item_name is None: 
                    prev_item_name = item['course_name']

                    #ECA
                    prev_name = item['user']

                    tee_time_list.append(tee_time)
                else:

                    #TMA
                    #if prev_item_name == item['course_name']:
                    #ECA - to resolve some bug
                    if prev_item_name == item['course_name'] and prev_name == item['user']:

                        tee_time_list.append(tee_time)
                    else:
                        #as long as diff from prev item, add to DB
                        courseNamePrev = Course.objects(name=prev_item_name).first()

                        #TMA
                        #aBookingUpload = Booking(name=name,courseName=courseNamePrev,tee_time=tee_time_list).save()
                        #prev_item_name = item['course_name']
                        #ECA - to resolve some bug
                        namePrev = User.objects(email=prev_name).first()
                        aBookingUpload = Booking(name=namePrev,courseName=courseNamePrev,tee_time=tee_time_list).save()
                        prev_item_name = item['course_name']
                        prev_name = item['user']

                        tee_time_list = []
                        tee_time_list.append(tee_time)
            #This is to add to booking DB if last two item is the same
            aBookingUpload = Booking(name=name,courseName=courseName,tee_time=tee_time_list).save()
                
        elif type == 'course':
            for item in list(dict_reader):
                name = item['course']
                indexUpload = item['index'].strip("[]").split(", ")
                parUpload = item['par'].strip("[]").split(", ")
                distUpload = item['dist'].strip("[]").split(", ")

                #TMA
                #holesDetail = HoleUploadInfo(index=indexUpload,par=parUpload,dist=distUpload).save()
                #ECA
                uploadBatch = []
                for row, value in enumerate(indexUpload): 
                    uploadItem = Hole(index=indexUpload[row],par=parUpload[row],dist=distUpload[row]).save()
                    uploadBatch.append(uploadItem)

                image = item['image_url']
                description = item['description']
                aCourseUpload = Course(name=name, holesDetail=uploadBatch, image=image, description=description).save()
        
        return render_template("upload.html", aUser=current_user.name)

controllers/dashboard.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import login_required, current_user
from models.courses import Course, HoleUploadInfo
from models.booking import Booking
from models.users import User
from datetime import datetime, timedelta

dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/dashboard', methods=['GET','POST'])
@login_required
def render_dashboard():
    #ECA
    getUserBookingName = request.values.get('userByBooking')
    getUserLoginObject = User.objects(name=getUserBookingName).first()
    filterUser = request.values.get('filterUser')

    checkCourse = request.form.get("courseSelect")
    if checkCourse is not None:
        courseSelectName = checkCourse
        courseSelect = Course.objects(name=courseSelectName).first()
        courseList = Course.objects()

        #TMA
        #courseBooking = Booking.objects(courseName=courseSelect)
        #ECA
        if filterUser == "":
            courseBooking = Booking.objects(courseName=courseSelect)
        else:
            courseBooking = Booking.objects(courseName=courseSelect,name=getUserLoginObject)

        #to check if there are any booking against the selection
        if len(courseBooking) > 0:
            holes_duration = []
            #just to calculate the holes duration for the course
            for i in courseList: 
                if i['name'] == courseSelectName:
                    duration = 0

                    #TMA
                    #for x in range(len(i['holesDetail']['index'])):
                    #    index = int(i['holesDetail']['index'][x])
                    #    par = int(i['holesDetail']['par'][x])
                    #    dist = int(i['holesDetail']['dist'][x])
                    #ECA
                    for row, hole in enumerate(i['holesDetail']):
                        index = int(hole['index'])
                        par = int(hole['par'])
                        dist = int(hole['dist'])

                        if index <= 6: setupTime = par*180
                        elif index <= 12: setupTime = par*150
                        else: setupTime = par*120
                        #set multipler as Play Time is 60s times X
                        multipler = dist//100 + 1
                        if dist > 500: multipler = 6
                        elif dist%100 == 0: multipler+1
                        playTime = 60*multipler
                        holes_duration.append(playTime+setupTime)
            accumulated_duration = [0]
            #To calculate duration per hole in total
            for i, t in enumerate(holes_duration):
                accumulated_duration.append(accumulated_duration[i] + t)
            #to run though all aviliable booking
            hole_start_time = []
            dict_id = 1
            courseBookingID = {}
            for o in courseBooking:
                tee_time = o['tee_time']
                for a in tee_time:
                    tee_time_date = datetime.strptime(a[0],'%d/%m/%Y %I:%M:%S %p')
                    #To add the start time per hole
                    for t in accumulated_duration:
                        hole_start_time.append(tee_time_date + timedelta(seconds = t))  
                    courseBookingID["Booking_"+str(dict_id)] = hole_start_time
                    hole_start_time = []
                    dict_id += 1
            charts = courseBookingID
            hole_labels = [f'Hole {i}' for i in range(1, len(accumulated_duration))] 
            hole_labels.insert(0, 'Start time')  
        else: return render_template('dashboard.html', aUser=current_user.name, sidebar=1, courses=Course.objects())
        if request.method == "GET":
                return render_template("dashboard.html", aUser=current_user.name, sidebar=1, courses=Course.objects(), chartData = jsonify({'charts': charts, 'labels': hole_labels}))
        elif request.method == "POST":
                return jsonify({'charts': charts, 'labels': hole_labels})

    #ECA
    if getUserBookingName is not None:
        user_booked_course = []
        user_booked_course_name = []
        for row, value in enumerate(Booking.objects()):
            if getUserBookingName == value['name']['name']:
                user_booked_course_name.append(value['courseName']['name'])
        for row, value in enumerate(Course.objects()):
            if value['name'] in user_booked_course_name:
                user_booked_course.append(Course.objects()[row])
        return render_template('dashboard.html', aUser=current_user.name, sidebar=1, courses=user_booked_course, filterByUser=1)            

    return render_template('dashboard.html', aUser=current_user.name, sidebar=1, courses=Course.objects())

templates/_render_field.html
{% macro render_field(field) %}

<div class="form-group">
    <label for="{{ field.name }}">{{ field.label.text }}</label>
    {{ field(class='form-control', **kwargs)|safe }}
    {% if field.errors %}
        <ul>
            {% for error in field.errors %}
            <li style="color:red">{{ error }}</li>
            {% endfor%}
        </ul>
    {% endif%}
</div>

{% endmacro %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="title icon" href="images/title-img.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css')}}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    
    <!-- navbar -->
    <nav class="navbar navbar-expand-md navbar-light">
      <button class="navbar-toggler ml-auto mb-2 bg-light" type="button" data-toggle="collapse" data-target="#myNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="myNavbar">
        <div class="container-fluid">
          <div class="row">
            <!-- sidebar -->
            <div class="col-xl-2 col-lg-3 col-md-4 sidebar fixed-top">
              <a href="#" class="navbar-brand text-white d-block mx-auto text-center py-3 mb-4 bottom-border">Reservation Portal</a>
              {% if sidebar != 1 %}
                {% if current_user.is_authenticated %}
                <div class="bottom-border pb-3">
                  <img src="{{ url_for('static', filename='img/admin.jpeg')}}" width="50" class="rounded-circle mr-3">
                  <a href="#" class="text-white">{{ aUser }} </a>
                </div>
                {% endif %}
                <ul class="navbar-nav flex-column mt-4">
                  {% if not current_user.is_authenticated %}
                  <li class="nav-item"><a href="{{ url_for('auth.login') }}" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-home text-light fa-lg mr-3"></i>Login</a></li>
                  <li class="nav-item"><a href="{{ url_for('auth.register') }}" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-user text-light fa-lg mr-3"></i>Register</a></li>
                  {% else %}
                  <li class="nav-item"><a href="courses" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-address-card text-light fa-lg mr-3"></i>Courses</a></li>
                  
                  <!-- ECA -->
                  <li class="nav-item"><a href="dashboard?userByBooking={{current_user.name}}" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-book-open text-light fa-lg mr-3"></i>View Booking</a></li>

                  {% if current_user.name == "Admin" %}
                  <li class="nav-item"><a href="dashboard" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-chart-area text-light fa-lg mr-3"></i>Dashboard</a></li>
                  <li class="nav-item"><a href="upload" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-cloud-upload-alt text-light fa-lg mr-3"></i>Upload</a></li>
                  {% endif %}
                {% endif %}
                </ul>
              {% endif %}
              {% block sidebaralt %}{% endblock %}
            </div>
            <!-- end of sidebar -->

            <!-- top-nav -->
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto bg-info fixed-top py-2 top-navbar">
              <div class="row align-items-center">
                <div class="col-md-4">
                  <h4 class="text-light text-uppercase mb-0">{% block panel %}{% endblock %}</h4>
                </div>
                {% if current_user.is_authenticated %}
                <div class="col-md-8"> 
                  <ul class="navbar-nav">
                    <li class="nav-item ml-auto"><a href="#" class="nav-link" data-toggle="modal" data-target="#sign-out"><i class="fas fa-sign-out-alt fa-lg"></i></a></li>
                  </ul>
                </div>
                {% endif %}
              </div>
            </div>
            <!-- end of top-nav -->
          </div>
        </div>
      </div>
    </nav>
    <!-- end of navbar -->

    <!-- modal -->
    <div class="modal fade" id="sign-out">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Want to leave?</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            Press logout to leave
          </div>
          <div class="modal-footer">
            <form action='/logout' method='GET'>
              <button type="button" class="btn btn-success" data-dismiss="modal" >Stay Here</button>
              <button type="submit" class="btn btn-danger"  id="logout">Logout</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- end of modal -->

    <!-- cards -->
    <section>
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto">
              <div class="row pt-md-5 ml-md-3 mt-md-3 mb-5">
                {% block mainblock %}
                {% endblock %}
              </div>
            </div>
          </div>
        </div>
    </section>

    <!-- end of cards -->
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/custom.js')}}"></script>
  </body>
</html>

templates/courseDetail.html
{% from "_render_field.html" import render_field %}
{% extends "base.html" %}
{% block panel %} {{aCourseName}} {% endblock %}
{% block title %} {{aCourseName}} {% endblock %}
{% block mainblock %}
<div class="col-xl-6 col-sm-6 p-2">
    <div class="card card-common">
    <img height=100px width=80% src="{{aCourse.image}}">
    <h5>{{aCourse.name}}</h5>
    {{aCourse.description}}
    </div>
</div>
<div class="col-xl-6 col-sm-6 p-2">
    <div class="card card-common">
    <div class="form">
        <form action="/courseDetail" method="POST">
            <fieldset>
                <legend>Select Tee Off Time</legend>
                <input name="type" type="hidden" value="courseBook">
                <label for="tee_time">Tee_time</label>
                <input type="datetime-local" id="tee_time" name="tee_time">
                <input name="courseType" type="hidden" value="{{aCourse.name}}">
                <input type="submit" value="Submit">
            </fieldset>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/courses.html
{% from "_render_field.html" import render_field %}
{% extends "base.html" %}
{% block panel %} Course {% endblock %}
{% block title %} Course {% endblock %}
{% block mainblock %}
{% if type %}
    <div>Booking successfully</div>
{% endif %}
{% for aCourse in courses %}
{% if loop.index%3 == 1 %}
    <div class="row">
{% endif %}
    <div class="col">
        <div class="card card-body">
            <div class="courseView">
                <img height=100px width=80% src="{{aCourse.image}}">
                <h5>{{aCourse.name}}</h5>
                {{aCourse.description}}
                <br>
                <div class="form">
                    <form action="/courses" method="POST">
                        <fieldset>
                        <input name="type" type="hidden" value="courseSelect">
                        <input name="courseType" type="hidden" value="{{aCourse.name}}">
                        <input type="submit" value="Book">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% if loop.index%3 == 0 %}
    </div>
{% endif %}   
{% endfor %}
{% endblock %}

templates/dashboard.html
{% from "_render_field.html" import render_field %}
{% extends "base.html" %}
{% block panel %} Dashboard {% endblock %}
{% block title %} Dashboard {% endblock %}
{% block sidebaralt %} 
    <ul class="navbar-nav flex-column mt-4">
        <li class="nav-item"><a href="courses" class="nav-link text-white p-3 mb-2 sidebar-link"><i class="fas fa-address-card text-light fa-lg mr-3"></i>Back to Course</a></li>
    </ul>

    <!-- ECA -->
    <input type="hidden" id="getUser" value="{{aUser}}"/>
    <input type="hidden" id="filterUser" value="{{filterByUser}}"/>

    <label for="courseList">
        <select name="courseList" id="courseList">
            <option disabled selected>Select One Course</option>
            {% for aCourse in courses %}
                <option value="{{aCourse.name}}">{{aCourse.name}}</option>
            {% endfor %}
        </select>
    </label>
{% endblock %}
{% block mainblock %}
<div class="col-sm-11 p-2">
    <div class="card card-common">
        <div class="form">
            <legend>Show Schedule</legend>
            <div class="chart-container">
                <canvas id="myChart"></canvas>
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
<script src="{{ url_for('static', filename='js/myLineChartAJAX.js') }}"></script>


{% endblock %}

templates/login.html
{% from "_render_field.html" import render_field %}
{% extends "base.html" %}
{% block panel %} Login {% endblock %}
{% block title %} Login {% endblock %}
{% block mainblock %}
<div class="col-xl-6 col-sm-6 p-2">
    <div class="card card-common">
    <div class="form">
        <form action="/login" method="POST">
            <fieldset>
                <legend>Login</legend>
                {{ render_field(RegistrationForm.email, type="email", placeholder="Enter email", id="email") }}
                
                {{ render_field(RegistrationForm.password, type="password", placeholder="Enter password", id="password") }}
                
                <input type="checkbox" id="remember-me" name="remember-me">
                <label for="remember-me">Remember me</label>
                <br><br>
                <input type="submit" value="Submit">
            </fieldset>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/register.html
{% from "_render_field.html" import render_field %}
{% extends "base.html" %}
{% block panel %} Register {% endblock %}
{% block title %} Register {% endblock %}
{% block mainblock %}

<div class="col-xl-6 col-sm-6 p-2">
    <div class="card card-common">
    <div class="form">
        <form action="/register" method="POST">
            <fieldset>
                <legend>Register</legend>
                {{ render_field(RegistrationForm.email, type="email", placeholder="Enter email", id="email") }}
                
                {{ render_field(RegistrationForm.password, type="password", placeholder="Enter password", id="password") }}
                
                {{ render_field(RegistrationForm.name, type="text", id="name") }}
                <input type="checkbox" id="remember-me" name="remember-me">
                <label for="remember-me">Remember me</label>
                <br><br>
                <input type="submit" value="Submit">
            </fieldset>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/upload.html
{% from "_render_field.html" import render_field %}
{% extends "base.html" %}
{% block panel %} UPLOAD {% endblock %}
{% block title %} UPLOAD {% endblock %}
{% block mainblock %}
<div class="col-xl-6 col-sm-6 p-2">
    <div class="card card-common">
    <div class="form">
        <form action="/upload" method="POST" enctype="multipart/form-data">
            <fieldset>
                <legend>Upload recordings</legend>
                <label for='upload'>Upload CSV file</label><br>
                <label>with data type of: </label>
                <select name="type">
                    <option value="course" selected>Course</option>
                    <option value="booking">Booking</option>
                </select><br>
                <input name="type" type="hidden" value="upload">
                <input class="upload" id='upload' name='file' type='file' accept='.csv' required>
                <br>
                <input type="submit" value="Upload" type="Upload">
            </fieldset>
        </form>
    </div>
</div>
</div>
{% endblock %}